version: '2.1'
services:
  app:
    build:
      context: ./
    restart: always
    container_name: app
    image: rest
    ports:
    - 8080:8080
    environment:
      JAVA_OPTS: "-Xmx1024M -Xms1024M"
  database:
    image: mysql:5.7
    ports:
    - "33061:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: secret